version = 0.1
[default.deploy.parameters]
stack_name = "customers-api"
resolve_s3 = true
s3_prefix = "customers-api"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
